model_list:
  - model_name: default-model
    litellm_params:
      model: ollama_chat/gpt-oss:20b
      api_base: http://host.docker.internal:11434

  - model_name: gpt-oss:20b
    litellm_params:
      model: ollama_chat/gpt-oss:20b
      api_base: http://host.docker.internal:11434

  - model_name: openrouter-model
    litellm_params:
      model: openrouter/z-ai/glm-4.5-air:free
      api_key: os.environ/OPENROUTER_KEY

  - model_name: openai-model
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

litellm_settings:
  drop_params: true

general_settings:
  master_key: sk-home-agent-litellm-key
